server:
  address: 0.0.0.0
  port: 9999
  servlet:
    context-path: /api
spring:
  application:
    name: mall-backend
  data:
    redis:
      host: localhost
      port: 6379
      # 过期时间
      time-to-live: 3600000
      timeout: 10000ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/youlai?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
  mail:
    host: smtp.qq.com
    port: 465
    username: 2576354261@qq.com
    password: rdfxgaekyinbdjai
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465


#mybatis-plus的实体类取别名，dao接口映射文件的位置，日志
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.mall.backend.pojo.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

captcha:
  expire-in-seconds: 300

jwt:
  secret: TQGHrlrMplPQG+SLoHOoj0yzBgSKXqIdmsq0BY9DFss=
  expire-in-seconds: 3600
  refresh-expire-in-seconds: 86400

# application.yml
file:
  upload:
    path: ./uploads

